apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "push-gateway.fullname" . }}-push-config
data:
  push_config.yaml: |-
    push:
      apns:
{{- if .Values.pushConfig.apns.configs -}}
{{- with .Values.pushConfig.apns.configs -}}
        {{ . | toYamlPretty | nindent 8 }}
{{- end }}
{{- else }}
          []
{{- end }}
      firebase:
{{- if .Values.pushConfig.firebase.configs -}}
{{- with .Values.pushConfig.firebase.configs -}}
        {{ toYamlPretty . | nindent 8 }}
{{- end }}
{{- else }}
          []
{{- end }}
