-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgWhAuh2VGjIJg4wqk
rNHge7Tx4pDARpZLh2QAqUUFSDuhRANCAAQSd3mWLgCYJSpGOkVIxWexYzkYz0T5
jU944/o6PBQFlIS/fvMQxI2wNhH8Pfjk6Bz6rQbq9A1brXdG8pfhkRaa
-----END PRIVATE KEY-----
